# Generated by Django 4.2.4 on 2024-12-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biko_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('Mevcut Kadro', 'Mevcut Kadro'), ('İlave Kadro', 'İlave Kadro')], max_length=100)),
                ('replacement_for', models.CharField(blank=True, max_length=100, null=True)),
                ('new_task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('work_type', models.CharField(choices=[('Tam Zamanlı', 'Tam Zamanlı'), ('Yarı Zamanlı', 'Yarı Zamanlı')], max_length=50)),
                ('request_reason', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('personnel_count', models.PositiveIntegerField()),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biko_hr.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biko_hr.organization')),
                ('task_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biko_hr.job')),
            ],
        ),
    ]
