# Generated by Django 5.0.4 on 2024-12-26 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0002_profile_location_profile_organization_and_more'),
        ('jobrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.location'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.organization'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='position_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.position'),
        ),
    ]
