# Generated by Django 4.2.4 on 2024-12-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0003_profile_location_profile_organization_and_more'),
        ('jobrequest', '0002_jobrequest_position_type_2_alter_jobrequest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='task_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biko_hr.incubationjob'),
        ),
    ]
