# Generated by Django 5.0.4 on 2024-12-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0002_alter_jobrequest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='position_type_2',
            field=models.CharField(blank=True, choices=[('Mevcut Kadro', 'Mevcut Kadro'), ('İlave Kadro', 'İlave Kadro')], max_length=100, null=True),
        ),
    ]
