# Generated by Django 4.2.4 on 2024-12-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0008_alter_incubationjob_category'),
        ('jobrequest', '0003_alter_jobrequest_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequest',
            old_name='experience_years',
            new_name='desired_experience_years',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='personnel_count',
            new_name='desired_personnel_count',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='start_date',
            new_name='desired_start_date',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='new_task_name',
            new_name='new_position_name',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='education',
            new_name='required_education_level',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='position_type_2',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='task_name',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='position_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.position'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='request_status_hr',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='request_status_organization_manager',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='position_type',
            field=models.CharField(blank=True, choices=[('Mevcut Kadro', 'Mevcut Kadro'), ('İlave Kadro', 'İlave Kadro')], max_length=100, null=True),
        ),
    ]
