# Generated by Django 5.0.4 on 2024-12-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobrequest", "0003_remove_taskrequest_personnel_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrequest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskrequest",
            name="education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="taskrequest",
            name="experience_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskrequest",
            name="new_task_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="taskrequest",
            name="personnel_count",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskrequest",
            name="special_requirements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskrequest",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskrequest",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("Tam Zamanlı", "Tam Zamanlı"),
                    ("Yarı Zamanlı", "Yarı Zamanlı"),
                ],
                default="Mevcut Kadro",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taskrequest",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("Mevcut Kadro", "Mevcut Kadro"),
                    ("İlave Kadro", "İlave Kadro"),
                ],
                max_length=50,
            ),
        ),
    ]
