# Generated by Django 4.2.4 on 2024-12-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0004_rename_experience_years_jobrequest_desired_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='request_status_hr',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='request_status_organization_manager',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
    ]
