# Generated by Django 5.0.4 on 2024-12-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biko_hr", "__first__"),
        ("jobrequest", "0005_remove_taskrequest_assigned_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskrequest",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="biko_hr.location"
            ),
        ),
        migrations.AlterField(
            model_name="taskrequest",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="biko_hr.organization"
            ),
        ),
        migrations.AlterField(
            model_name="taskrequest",
            name="task_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="biko_hr.task",
            ),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
