# Generated by Django 5.0.4 on 2024-12-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biko_hr", "0010_alter_application_candidate"),
        ("jobrequest", "0005_alter_jobrequest_request_status_hr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="candidates",
            field=models.ManyToManyField(
                related_name="job_requests", to="biko_hr.candidate"
            ),
        ),
    ]
