# Generated by Django 5.0.4 on 2024-12-26 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.position'),
        ),
    ]
