# Generated by Django 4.2.4 on 2024-12-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0002_jobcategory_position_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.position'),
        ),
    ]
