# Generated by Django 4.2.4 on 2024-12-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobrequest', '0003_alter_jobrequest_task_name'),
        ('biko_hr', '0003_profile_location_profile_organization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='candidate',
            name='desired_locations',
            field=models.ManyToManyField(to='biko_hr.location'),
        ),
        migrations.AddField(
            model_name='incubationjob',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.jobcategory'),
        ),
        migrations.AddField(
            model_name='incubationjob',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.organization'),
        ),
        migrations.AddField(
            model_name='incubationjob',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.position'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
