# Generated by Django 4.2.4 on 2024-12-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0005_alter_incubationjob_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubationjob',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.jobcategory'),
        ),
    ]
