# Generated by Django 4.2.4 on 2025-02-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0010_alter_application_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='uploaded_resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
