# Generated by Django 4.2.4 on 2025-02-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0011_alter_application_uploaded_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='desired_locations',
            field=models.ManyToManyField(blank=True, null=True, to='biko_hr.location'),
        ),
    ]
