# Generated by Django 4.2.4 on 2025-02-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0014_alter_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='school_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
