# Generated by Django 4.2.4 on 2025-02-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0015_alter_candidate_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
