# Generated by Django 4.2.4 on 2025-03-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0017_application_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewattributes',
            name='technical_skills',
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='Appearance',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='Behaviour',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='Communucation',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='Dedication_to_job',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='Explanation',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='HR_evaluation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='Succes',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='Team_work',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='advancement',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='leadership',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='manager_evaluation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='open_to_improvement',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewattributes',
            name='technical_qualification',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewattributes',
            name='problem_solving',
            field=models.CharField(blank=True, choices=[('Zayıf', 'Zayıf'), ('Gelişmesi Gerekli', 'Gelişmesi Gerekli'), ('Beklentileri Karşılıyor', 'Beklentileri Karşılıyor'), ('Başarılı', 'Başarılı'), ('Çok Başarılı', 'Çok Başarılı')], max_length=100, null=True),
        ),
    ]
