# Generated by Django 4.2.4 on 2025-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0018_remove_interviewattributes_technical_skills_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.RemoveField(
            model_name='reference',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='reference_role',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='weaknesses',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='work_duration',
        ),
        migrations.AddField(
            model_name='reference',
            name='advancements',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='reference',
            name='areas_for_improvement',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='reference',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='desired_position',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='reference',
            name='dicipline',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='reference',
            name='further_explanation',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='reference',
            name='info_retriever_name',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='reference',
            name='major_error',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='reference',
            name='referance_name',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='reference',
            name='refereance_relation_to_candidate',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_outcome',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_title',
            field=models.CharField(default='Not specified', max_length=15),
        ),
        migrations.AddField(
            model_name='reference',
            name='responsibility',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='reference',
            name='work_duration_with_company',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='reference',
            name='work_duration_with_referee',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='duties',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reason_for_leaving',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_company',
            field=models.CharField(default='Not specified', max_length=15),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_phone',
            field=models.CharField(default='Not specified', max_length=15),
        ),
        migrations.AlterField(
            model_name='reference',
            name='strengths',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='would_work_again',
            field=models.TextField(default='Not specified'),
        ),
    ]
