# Generated by Django 4.2.4 on 2025-03-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biko_hr', '0019_alter_reference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewattributes',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biko_hr.interview'),
        ),
    ]
