# Generated by Django 5.1.4 on 2024-12-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_alter_candidate_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='education_level',
            field=models.CharField(choices=[('Okuma Yazma Belgesi', 'Okuma Yazma Belgesi'), ('İlkokul', 'İlkokul'), ('Ortaokul', 'Ortaokul'), ('Lise', 'Lise'), ('Üniversite', 'Üniversite'), ('postgraduate', 'Yüksek Lisans ve Üzeri')], max_length=20),
        ),
    ]
