# Generated by Django 5.0.4 on 2024-12-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('hr_staff', 'HR Staff'), ('organization_staff', 'Organization Staff'), ('Director', 'Director')], max_length=50),
        ),
    ]
